"""Constants for Gauntlet II maze objects, flags, and tricks."""

from enum import IntEnum


class MazeObj(IntEnum):
    """Maze object IDs (names matching names in IDA)."""
    TILE_FLOOR = 0
    TILE_STUN = 1
    WALL_REGULAR = 2
    WALL_MOVABLE = 3
    WALL_SECRET = 4
    WALL_DESTRUCTABLE = 5
    WALL_RANDOM = 6
    WALL_TRAPCYC1 = 7
    WALL_TRAPCYC2 = 8
    WALL_TRAPCYC3 = 9
    TILE_TRAP1 = 10
    TILE_TRAP2 = 11
    TILE_TRAP3 = 12
    DOOR_HORIZ = 13
    DOOR_VERT = 14
    PLAYERSTART = 15
    EXIT = 16
    EXITTO6 = 17
    MONST_GHOST = 18
    MONST_GRUNT = 19
    MONST_DEMON = 20
    MONST_LOBBER = 21
    MONST_SORC = 22
    MONST_AUX_GRUNT = 23
    MONST_DEATH = 24
    MONST_ACID = 25
    MONST_SUPERSORC = 26
    MONST_IT = 27
    GEN_GHOST1 = 28
    GEN_GHOST2 = 29
    GEN_GHOST3 = 30
    GEN_GRUNT1 = 31
    GEN_GRUNT2 = 32
    GEN_GRUNT3 = 33
    GEN_DEMON1 = 34
    GEN_DEMON2 = 35
    GEN_DEMON3 = 36
    GEN_LOBBER1 = 37
    GEN_LOBBER2 = 38
    GEN_LOBBER3 = 39
    GEN_SORC1 = 40
    GEN_SORC2 = 41
    GEN_SORC3 = 42
    GEN_AUX_GRUNT1 = 43
    GEN_AUX_GRUNT2 = 44
    GEN_AUX_GRUNT3 = 45
    TREASURE = 46
    TREASURE_LOCKED = 47
    TREASURE_BAG = 48
    FOOD_DESTRUCTABLE = 49
    FOOD_INVULN = 50
    POT_DESTRUCTABLE = 51
    POT_INVULN = 52
    KEY = 53
    POWER_INVIS = 54
    POWER_REPULSE = 55
    POWER_REFLECT = 56
    POWER_TRANSPORT = 57
    POWER_SUPERSHOT = 58
    POWER_INVULN = 59
    MONST_DRAGON = 60
    HIDDENPOT = 61
    TRANSPORTER = 62
    FORCEFIELDHUB = 63


# Flags for levels
LFLAG1_ODDANGLE_GHOSTS = 0x01000000
LFLAG1_ODDANGLE_GRUNTS = 0x02000000
LFLAG1_ODDANGLE_DEMONS = 0x04000000
LFLAG1_ODDANGLE_LOBBERS = 0x08000000
LFLAG1_ODDANGLE_SORCERERS = 0x10000000
LFLAG1_ODDANGLE_AUX_GRUNTS = 0x20000000
LFLAG1_ODDANGLE_DEATHS = 0x40000000
LFLAG1_INVIS_TRAPWALLS = 0x80000000

LFLAG2_FAST_GHOSTS = 0x010000
LFLAG2_FAST_GRUNTS = 0x020000
LFLAG2_FAST_DEMONS = 0x040000
LFLAG2_FAST_LOBBERS = 0x080000
LFLAG2_FAST_SORCERERS = 0x100000
LFLAG2_FAST_AUX_GRUNTS = 0x200000
LFLAG2_FAST_DEATHS = 0x400000
LFLAG2_INVIS_ALLWALLS = 0x800000

LFLAG3_RANDOMFOOD_MASK = 0x0700
LFLAG3_WALLS_CYCLIC = 0x0800
LFLAG3_WALLS_DELETABLE1 = 0x1000
LFLAG3_WALLS_DELETABLE2 = 0x2000
LFLAG3_EXIT_MOVES = 0x4000
LFLAG3_EXIT_CHOOSEONE = 0x8000

LFLAG4_SHOTS_STUN = 0x01
LFLAG4_SHOTS_HURT = 0x02
LFLAG4_TRAPS_LOCAL = 0x04
LFLAG4_TRAPS_RANDOM = 0x08
LFLAG4_WRAP_V = 0x10
LFLAG4_WRAP_H = 0x20
LFLAG4_EXIT_FAKE = 0x40
LFLAG4_PLAYER_OFFSCREEN = 0x80

MAZE_FLAG_STRINGS: dict[int, str] = {
    LFLAG1_ODDANGLE_GHOSTS: "ODDANGLE_GHOSTS",
    LFLAG1_ODDANGLE_GRUNTS: "ODDANGLE_GRUNTS",
    LFLAG1_ODDANGLE_DEMONS: "ODDANGLE_DEMONS",
    LFLAG1_ODDANGLE_LOBBERS: "ODDANGLE_LOBBERS",
    LFLAG1_ODDANGLE_SORCERERS: "ODDANGLE_SORCERERS",
    LFLAG1_ODDANGLE_AUX_GRUNTS: "ODDANGLE_GRUNTS",
    LFLAG1_ODDANGLE_DEATHS: "ODDANGLE_DEATHS",
    LFLAG1_INVIS_TRAPWALLS: "INVIS_TRAPWALLS",
    LFLAG2_FAST_GHOSTS: "FAST_GHOSTS",
    LFLAG2_FAST_GRUNTS: "FAST_GRUNTS",
    LFLAG2_FAST_DEMONS: "FAST_DEMONS",
    LFLAG2_FAST_LOBBERS: "FAST_LOBBERS",
    LFLAG2_FAST_SORCERERS: "FAST_SORCERERS",
    LFLAG2_FAST_AUX_GRUNTS: "FAST_AUX_GRUNTS",
    LFLAG2_FAST_DEATHS: "FAST_DEATHS",
    LFLAG2_INVIS_ALLWALLS: "INVIS_ALLWALLS",
    LFLAG3_WALLS_CYCLIC: "WALLS_CYCLIC",
    LFLAG3_WALLS_DELETABLE1: "WALLS_DELETABLE1",
    LFLAG3_WALLS_DELETABLE2: "WALLS_DELETABLE2",
    LFLAG3_EXIT_MOVES: "EXIT_MOVES",
    LFLAG3_EXIT_CHOOSEONE: "EXIT_CHOOSE_ONE",
    LFLAG4_SHOTS_STUN: "SHOTS_STUN",
    LFLAG4_SHOTS_HURT: "SHOTS_HURT",
    LFLAG4_TRAPS_LOCAL: "TRAPS_LOCAL",
    LFLAG4_TRAPS_RANDOM: "TRAPS_RANDOM",
    LFLAG4_WRAP_V: "WRAP_V",
    LFLAG4_WRAP_H: "WRAP_H",
    LFLAG4_EXIT_FAKE: "EXIT_FAKE",
    LFLAG4_PLAYER_OFFSCREEN: "PLAYER_OFFSCREEN",
}

# Trick constants
TRICK_NONE = 0x00
TRICK_TRANSPORT1 = 0x01
TRICK_TRANSPORT2 = 0x02
TRICK_TRANSPORT3 = 0x03
TRICK_TRANSPORT4 = 0x04
TRICK_WATCHSHOOT1 = 0x05
TRICK_WATCHSHOOT2 = 0x06
TRICK_SAVESUPERSHOTS = 0x07
TRICK_NOUSEINVUL = 0x08
TRICK_NOGETHIT = 0x09
TRICK_PUSHWALL = 0x0A
TRICK_NOFOOLED = 0x0B
TRICK_NOGREEDY1 = 0x0C
TRICK_NOGREEDY2 = 0x0D
TRICK_DIET = 0x0E
TRICK_BEPUSHY = 0x0F
TRICK_IT = 0x10
TRICK_NOHURTFRIENDS = 0x11

MAZE_SECRET_STRINGS: dict[int, str] = {
    TRICK_NONE: "No trick",
    TRICK_TRANSPORT1: "Try Transportability (onto demon)",
    TRICK_TRANSPORT2: "Try Transportability (onto death)",
    TRICK_TRANSPORT3: "Try Transportability (into exit)",
    TRICK_TRANSPORT4: "Try Transportability (onto secret wall)",
    TRICK_WATCHSHOOT1: "Watch What You Shoot (shoot foods)",
    TRICK_WATCHSHOOT2: "Watch What You Shoot (shoot secret walls)",
    TRICK_SAVESUPERSHOTS: "Save Super Shots",
    TRICK_NOUSEINVUL: "Don't Use Invulnerability",
    TRICK_NOGETHIT: "Don't Get Hit (while killing a dragon)",
    TRICK_PUSHWALL: "Try Pushing a Wall",
    TRICK_NOFOOLED: "Don't Be Fooled",
    TRICK_NOGREEDY1: "Don't Be Greedy (no keys or potions)",
    TRICK_NOGREEDY2: "Don't Be Greedy (no treasure)",
    TRICK_DIET: "Go On a Diet (no food)",
    TRICK_BEPUSHY: "Be Pushy",
    TRICK_IT: "IT Could Be Nice",
    TRICK_NOHURTFRIENDS: "Don't Hurt Friends",
}
